# Site settings
title: Interative Integrity
email:
description: > # this means to ignore newlines until "baseurl:"
  This is just my blogging page, go back to huntercaron.com for information on me rather than reading my weird thoughts.
baseurl: "/HCDesignBlog" # the subpath of your site, e.g. /blog/
url: "http://huntercaron.com/" # the base hostname & protocol for your site

twitter_username: hunterhcaron
github_username:  Mithon

# Build settings
markdown: kramdown
